# Generated by Django 3.2.10 on 2021-12-23 13:38

from django.db import migrations, models
import django.utils.timezone
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryextended',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=photologue.models.get_storage_path, verbose_name='image'),
            preserve_default=False,
        ),
    ]
