# Generated by Django 3.2.10 on 2021-12-27 08:26

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_custom', '0003_remove_galleryextended_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryextended',
            name='image',
            field=models.ImageField(default=None, upload_to=photologue.models.get_storage_path, verbose_name='image'),
        ),
    ]
